language: android
sudo: false
jdk: openjdk7
android:
  components:
    - tools
    - build-tools-23.0.3
    - extra-android-support
    - extra-android-m2repository
    - android-23
  licenses:
    - '.+'
before_script:
  - export TERM=dumb
  - curl -L http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O
  - chmod u+x android-ndk-r10e-linux-x86_64.bin
  - ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - rm android-ndk-r10e-linux-x86_64.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
  - export PATH=$PATH:${ANDROID_NDK_HOME}
  - find $ANDROID_NDK_HOME -type d
  - env
  - pwd
script:
  - gpg --keyserver hkp://hkps.pool.sks-keyservers.net --recv-key 0x8D29319A
  - gpg --keyserver hkp://hkps.pool.sks-keyservers.net --recv-key 0x0E604491
  - gpg --keyserver hkp://hkps.pool.sks-keyservers.net --recv-key 0x7E045F8D
  - bash ./download.sh
  - bash ./cleanup.sh
  - bash ./build.sh
  - bash ./package.sh
  - cd Android
  - ./gradlew clean assemble -q -S
  - ./gradlew check -q -S
after_script:
  - cat app/build/outputs/lint-results.xml
  - cd ..
  - cat expat-2.2.0/config.log
  - cat expat-2.2.0/configure.log
  - cat expat-2.2.0/make.install.log
  - cat expat-2.2.0/make.log
  - cat openssl-1.0.2h/configure.log
  - cat openssl-1.0.2h/make.depend.log
  - cat openssl-1.0.2h/make.log
  - cat openssl-1.0.2h/make.install_sw.log
