language: android
sudo: false
jdk: openjdk7
android:
  components:
    - tools
    - build-tools-23.0.3
    - extra-android-support
    - extra-android-m2repository
    - android-23
  licenses:
    - '.+'
before_script:
  - export TERM=dumb
  - curl -L http://dl.google.com/android/repository/android-ndk-r12-linux-x86_64.zip -O
  - unzip -q android-ndk-r12-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r12
  - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
  - export PATH=$PATH:${ANDROID_NDK_HOME}
  - export _NO_CHECK_SIGNATURE=true
script:
  - gpg -q --keyserver hkp://hkps.pool.sks-keyservers.net --recv-key 0x8D29319A
  - gpg -q --keyserver hkp://hkps.pool.sks-keyservers.net --recv-key 0x0E604491
  - gpg -q --keyserver hkp://hkps.pool.sks-keyservers.net --recv-key 0x7E045F8D
  - bash ./download.sh
  - bash ./cleanup.sh
  - bash ./build.sh
  - bash ./package.sh
  - cd Android
  - ./gradlew clean assemble -q -S
  - ./gradlew check -q -S
